name: Go CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  vet_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run make target
      run: make ci

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.3.0
        args: --disable errcheck
